CREATE TABLE USUARIO(
    CPF CHAR(14) NOT NULL,
    RG CHAR(9),
    NOME VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(45) NOT NULL,
    SENHA VARCHAR(20) NOT NULL,
    
    CONSTRAINT PK_USUARIO PRIMARY KEY (CPF),
    CONSTRAINT CK_CPF check(regexp_like(CPF, '[0-9]{3}\.[0-9]{3}\.[0-9]{3}\-[0-9]{2}')),
    CONSTRAINT CK_RG check(regexp_like(RG, '[0-9]{2}\.[0-9]{3}\.[0-9]{3}\-[0-9]{1}'))
);

CREATE TABLE TIPO_USUARIO(
    CPF_USUARIO CHAR (14) NOT NULL,
    TIPO CHAR(1),
    
    CONSTRAINT PK_TIPO_USUARIO PRIMARY KEY (CPF_USUARIO,TIPO),
    CONSTRAINT FK_TIPO_USUARIO FOREIGN KEY (CPF_USUARIO) REFERENCES USUARIO(CPF),
    CONSTRAINT CK_TIPO CHECK (UPPER(TIPO) IN ('A','F','O')) 
);

CREATE TABLE PRODUTO(
    COD_PRODUTO INTEGER NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    DESCRICAO VARCHAR(45),
    LUCRO_ESPERADO INTEGER,
    QNTD_ESTOQUE INTEGER,    
    CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO)
);

CREATE SEQUENCE COD_PRODUTO START WITH 1 INCREMENT BY 1;

 CREATE OR REPLACE TRIGGER GERA_COD_PRODUTO 
    BEFORE INSERT ON PRODUTO
    FOR EACH ROW
    BEGIN
        select COD_PRODUTO.nextval INTO :NEW.COD_PRODUTO FROM dual;
    END;


CREATE TABLE REPOSICAO(
    N_PEDIDO INTEGER NOT NULL,
    COD_PRODUTO INTEGER NOT NULL,
    P_COMPRA NUMERIC NOT NULL,
    P_VENDA NUMERIC NOT NULL,
    QNTD_REPOSICAO INTEGER NOT NULL,
    DATA_REPOSICAO DATE NOT NULL,
    
    CONSTRAINT PK_REPOSICAO PRIMARY KEY (N_PEDIDO,COD_PRODUTO),
    CONSTRAINT FK_REPOSICAO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO) 
);

CREATE SEQUENCE N_PEDIDO START WITH 1 INCREMENT BY 1;

 CREATE OR REPLACE TRIGGER GERA_N_PEDIDO 
    BEFORE INSERT ON REPOSICAO
    FOR EACH ROW
    BEGIN
        select N_PEDIDO.nextval INTO :NEW.N_PEDIDO FROM dual;
    END
 ;
 
 CREATE TABLE REPOSICAO(
    N_PEDIDO INTEGER NOT NULL,
    COD_PRODUTO INTEGER NOT NULL,
    P_COMPRA NUMERIC NOT NULL,
    P_VENDA NUMERIC NOT NULL,
    QNTD_REPOSICAO INTEGER NOT NULL,
    DATA_REPOSICAO DATE NOT NULL,
    
    CONSTRAINT PK_REPOSICAO PRIMARY KEY (N_PEDIDO,COD_PRODUTO),
    CONSTRAINT FK_REPOSICAO FOREIGN KEY(COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO) 
);

 CREATE TABLE VENDA(
) 

